version: '3.1'
services:
  main-server:
    build: main
    container_name: ewm-main-server
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - statistics-server
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewmmain
        - SPRING_DATASOURCE_USER=root
        - SPRING_DATASOURCE_PASSWORD=root
        - statistics.server.address=http://statistics-server:9090

  main-db:
    image: postgres:13.7-alpine
    container_name: ewm-main-db
    ports:
      - "6543:5432"
    environment:
        - POSTGRES_DB=ewmmain
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  statistics-server:
    build: stat/server/
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - statistics-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://statistics-db:5432/ewmstatistics
        - SPRING_DATASOURCE_USER=root
        - SPRING_DATASOURCE_PASSWORD=root

  statistics-db:
    image: postgres:13.7-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstatistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root