version: '3.1'
services:
  stats-server:
    build: stat/server
    container_name: stats_server
    ports:
      - "9090:9090"
    depends_on: [ stat-db ]
    environment:
      - DB_NAME=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stat_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

