
create table if not exists hits
(
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app varchar(100) NOT NULL,
    uri varchar(300) NOT NULL,
    ip varchar(300) NOT NULL,
    timestamp timestamp WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);